services:
  - docker

before_install:
  - docker build -t sobh7771/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sobh7771/react-test yarn test

after_success:
  - docker build -t sobh7771/multi-client ./client
  - docker build -t sobh7771/multi-nginx ./nginx
  - docker build -t sobh7771/multi-server ./server
  - docker build -t sobh7771/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push sobh7771/multi-client
  - docker push sobh7771/multi-nginx
  - docker push sobh7771/multi-server
  - docker push sobh7771/multi-worker
