services:
  - docker

before_install:
  - docker build -t sobh7771/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sobh7771/react-test yarn test CI=true

after_success:
  - docker build -t sobh7771/multi-client ./client
  - docker build -t sobh7771/multi-nginx ./nginx
  - docker build -t sobh7771/multi-server ./server
  - docker build -t sobh7771/multi-worker ./worker
