services:
  client:
    image: sobh7771/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: sobh7771/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: sobh7771/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: sobh7771/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80
